# az ml data create --name diabetes-training-data --path ./production/data --type uri_folder --resource-group my-resource-group --workspace-name my-workspace
# az ml job create --file .\src\prod-job.yml --resource-group my-resource-group --workspace-name my-workspace
$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code: model
command: >-
  python train.py
  --training_data ${{inputs.training_data}}
  --reg_rate ${{inputs.reg_rate}}
inputs:
  training_data: 
    type: uri_folder 
    path: azureml:diabetes-prod-train-data:1
  reg_rate: 0.01
environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu@latest
compute: "tdg-ai-labeling-cluster"
experiment_name: "MLOps-learning"
description: "An experiment to complete the challenges in the Azure MLOps training https://learn.microsoft.com/en-us/training/paths/build-first-machine-operations-workflow/"