# name: Train Model in Dev and Prod

# on:
#   push:
#     branches:
#       - main

# jobs:
#   experiment:
#     name: Experiment (Dev)
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out repo
#         uses: actions/checkout@v4

#       - name: Install Azure ML CLI
#         run: az extension add -n ml -y

#       - name: Azure login
#         uses: azure/login@v1
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}

#       - name: Submit experiment job
#         id: experiment_job
#         run: |
#           az ml job create \
#             --file src/job.yml \
#             --resource-group <dev-resource-group> \
#             --workspace-name <dev-workspace> \
#             --set inputs.training_data=azureml:diabetes-dev-folder@latest \
#             --query name -o tsv > job_name.txt
#           job_name=$(cat job_name.txt)
#           az ml job show --name $job_name --resource-group <dev-resource-group> --workspace-name <dev-workspace> --query status -o tsv > job_status.txt
#           status=$(cat job_status.txt)
#           if [ "$status" != "Completed" ]; then
#             echo "Experiment job failed with status: $status"
#             exit 1
#           fi

#   production:
#     name: Production
#     runs-on: ubuntu-latest
#     needs: experiment
#     steps:
#       - name: Check out repo
#         uses: actions/checkout@v4

#       - name: Install Azure ML CLI
#         run: az extension add -n ml -y

#       - name: Azure login
#         uses: azure/login@v1
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}

#       - name: Submit production job
#         run: |
#           az ml job create \
#             --file src/job.yml \
#             --resource-group <prod-resource-group> \
#             --workspace-name <prod-workspace> \
#             --set inputs.training_data=azureml:diabetes-prod-folder@latest